/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Fatty.glb -o src/components/Fatty.jsx -k -K -r public 
Author: hodart (https://sketchfab.com/hodart)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spongebob-fish-incidental-90-1bb8ba21007949be9cfac235082bc7e3
Title: SpongeBob Fish - Incidental 90
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Fatty({animation,...props}) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/Fatty.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

   useEffect(() => {
      console.log('Loaded Materials:', materials);
      actions[animation]?.reset().fadeIn(0.24).play();
      return () => actions?.[animation]?.fadeOut(0.24);
    }, [animation]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={1.224}>
          <group name="138b36058ece4fc1b680787d5acb6e09fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_37" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_39" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <skinnedMesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.body} skeleton={nodes.Object_38.skeleton} />
                    <skinnedMesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.material} skeleton={nodes.Object_40.skeleton} />
                  </group>
                </group>
                <group name="body_low" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="eye_low" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="cs_master" position={[50, 1750, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={10} />
                <group name="cs_square_2" position={[50, 149.67, 0]} rotation={[Math.PI / 2, 0, 0]} scale={15.412} />
                <group name="cs_square" position={[150, 149.67, 0]} rotation={[Math.PI / 2, 0, 0]} scale={15.412} />
                <group name="cs_hips" position={[50, 1150, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={20.552} />
                <group name="cs_circle" position={[50, 450, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={20.552} />
                <group name="cs_neck" position={[50, 1450, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={20.552} />
                <group name="cs_head" position={[50, 1350, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={20.552} />
                <group name="cs_shoulder_left" position={[50, 1550, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={103.843} />
                <group name="cs_arm_fk" position={[150, 850, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={82.209} />
                <group name="cs_forearm_fk" position={[250, 850, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={82.209} />
                <group name="cs_sphere_012" position={[350, 250, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={20.552} />
                <group name="cs_sphere" position={[50, 250, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={20.552} />
                <group name="cs_hand" position={[50, 1950, 0]} rotation={[Math.PI / 2, 0, 0]} scale={30.825} />
                <group name="cs_shoulder_right" position={[50, 1650, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={103.843} />
                <group name="cs_thigh_fk" position={[50, 750, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={82.209} />
                <group name="cs_calf_fk" position={[50, 850, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={82.209} />
                <group name="cs_foot" position={[50, 1050, 0]} rotation={[Math.PI / 2, 0, 0]} scale={30.825} />
                <group name="cs_foot_roll" position={[50, 1250, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={59.158} />
                <group name="cs_foot001" position={[50, 1050, 0]} rotation={[Math.PI / 2, 0, 0]} scale={30.825} />
                <group name="cs_foot_01" position={[50, 1850, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={218.646} />
                <group name="cs_foot002" position={[50, 1050, 0]} rotation={[Math.PI / 2, 0, 0]} scale={30.825} />
                <group name="cs_toe" position={[50, 950, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={42.926} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Fatty.glb')
